name: Run Newman Tests

on:
  schedule:
    - cron: '0 8 * * *'  # 매일 오후 5시 (KST 기준, UTC 8시)

#  push:
  pull_request:
    branches:
      - main # 'main' 브랜치로 PR이 열리거나 병합 시도될 때만 실행
  workflow_dispatch:  # UI에서 수동 실행 가능

jobs:
  run_newman:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

