name: Rim Test  # 워크플로우 이름

on:     # 워크플로우가 언제 실행될지 설정하는 부분으로, 필수항목
  push: # 특정 브랜치로 push될때마다 실행하도록 설정 
    branches:
      - main
      
  workflow_dispatch:  # UI에서 수동 실행 가능

jobs:
  run_newman:
    runs-on: ubuntu-latest

    steps:
      # 1. 필수 설정 값으로, 보통 제일 먼저 쓰며 GitHub 리포지토리에서 소스 코드 또는 파일을 가져오는 역할
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Node.js to use npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # 특정 Node.js 버전을 사용하도록 설정

      # 3. Install Newman and Slack Reporter
      - name: Install Newman and Slack Reporter
        run: |
          npm install -g newman newman-reporter-slackmsg

      - name: Create Default Postman Environment
        run: |
          cat <<EOF > env.json
          {
            "id": "b978a6ba-1a76-43a5-badf-084c14613d20",
            "name": "Generated Environment",
            "values": [
              { "key": "userId", "value": "${{ secrets.API_NAME }}", "enabled": true },
              { "key": "password", "value": "${{ secrets.API_PWD }}", "enabled": true }
            ]
          }
          EOF
          echo "✅ Default env.json file created: $(pwd) "
          ls -alh ./env.json

      # 4. Check if collection file exists
      - name: Check if Login.json exists
        id: check_file
        run: |
          if [ ! -f ./Login.json ]; then
            echo "Collection file not found"
            echo "file_exists=false" >> $GITHUB_ENV
          else
            echo "file_exists=true" >> $GITHUB_ENV
          fi

      # 5. Run Newman Collection only if file exists
      - name: Run Newman Collection
        if: env.file_exists == 'true'
        run: |
          newman run ./Login.json \
            -r json,slackmsg \
            --environment ./env.json \
            --reporter-json-export newman-report.json \
            --reporter-slackmsg-token ${{ secrets.SLACK_BOT_TOKEN }} \
            --reporter-slackmsg-webhookurl ${{ secrets.SLACK_WEBHOOK_URL }} \
            --reporter-slackmsg-channel '#rim_api_noti'

      # 6. Notify Slack if collection file is not found  #longin.json 파일이 해당 경로에 없을때, 슬랙으로 에러 메세지 전송 
      - name: Notify Slack if Collection File is Missing
        if: env.file_exists == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            const payload = {
              text: '❌ Error: Collection file Login.json not found. Please check the file path.'
            };
            const webhookUrl = process.env.SLACK_WEBHOOK_URL;
            const response = await fetch(webhookUrl, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify(payload)
            });
            if (!response.ok) {
              throw new Error('Failed to send Slack notification');
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
